1 Read a .csv from URL with Pandas

In [29]:
import pandas as pd

In [30]:
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2021/E0.csv')

In [31]:
df_premier21.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97

In [32]:
df_premier21.rename(columns={'FTHG': 'Full Time Home Goals',
                              'FTAG': 'Full Time Away Goals',
                              'FTR': 'Full Time Result',
                              'HTHG': 'Half Time Home Goals',
                              'HTAG': 'Half Time Away Goals',
                              'HTR': 'Half Time Result'}, inplace=True)

In [33]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,Full Time Home Goals,Full Time Away Goals,Full Time Result,Half Time Home Goals,Half Time Away Goals,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,23/05/2021,16:00,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,23/05/2021,16:00,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

2 Read .csv from Multiple URLs with Pandas

In [34]:
root="https://www.football-data.co.uk/mmz4281/"

In [35]:
leagues=['E0', 'E1', 'E2', 'E3','EC']
frames=[]

In [36]:
for league in leagues:
    df = pd.read_csv(root + '2122' + '/' + league + '.csv', encoding='unicode_escape')
    frames.append(df)

In [37]:
len(frames)

5

In [38]:
frames[0]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [39]:
for league in leagues:
    for season in range(15,21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv', encoding='unicode_escape')
        frames.append(df)

In [40]:
len(frames)

35

In [41]:
dict_countries = {
    'Spanish La Liga': 'SP1',
    'Spanish Segunda Division': 'SP2',
    'German Bundesliga': 'D1',
    'English Premier League': 'E0',
    'English League 1': 'E2',
    'English League 2': 'E3',
    
}

In [42]:
dict_countries['Spanish La Liga']

'SP1'

In [43]:
for league in dict_countries:
    print( dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [ ]:
dict_countries[league]

'E3'

In [49]:
dict_historical_data = {}

for league in dict_countries:
    frames = []
    for season in range(15,21):
        file_path = root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv'
        df = pd.read_csv(file_path, encoding='unicode_escape')
        df.insert(1, 'season', str(season) + str(season+1))  # mieux que juste season
        frames.append(df)
    df_concat=pd.concat(frames, ignore_index=True)
    dict_historical_data[league] = df_concat

In [51]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])